title: "JV Engineering"

description: "Consultoria de alto nível em Engenharia, Simulação Computacional e Modelagem Matemática. Entregamos precisão, rigor analítico e soluções definitivas para desafios complexos em áreas STEM."

images:
  - "images/logo.png"

logo: "logo.png"

favicons:
  themeColor: "#0F172A"
  backgroundColor: "#0F172A"
  faviconColor: "#FFFFFF"

social:
  linkedin: "https://www.linkedin.com/in/joaovitormirandasousa"
  github: "https://github.com/joaovitormiranda-eng"
  email: "mailto:joaovitormonica87@gmail.com"
  whatsapp: "https://wa.me/5516981946642" # Se não quiser nem o ícone do zap, é só apagar essa linha!

location:
  - "Atendimento remoto • Brasil"

copyright: "© 2026 JV Engineering. Todos os direitos reservados."